server:
  port: 7777
spring:
  application:
    name: cloud-coupon-privoder
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.99.155.151:3306/xiaodingdang?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    database: 3
    host: 47.92.5.243
    port: 6379
    jedis:
      pool:
        max-idle: 30
        min-idle: 8
        max-active: 8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xld.pojo
