server:
  port: 4399
spring:
  application:
    name: seckill-service4399
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:
    url: jdbc:mysql://39.99.155.151:3306/xiaodingdang?serverTimezone=Asia/Shanghai
    username: root
    password: root
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
mybatis:
  mapper-locations: classpath:mapper/*.xml